### ISSUE TITLE
Popup always starts in insert mode

### ISSUE THREAD

**Issue by jphalip** [AlexGirardDev/HarpoonIJ#18]
I use IdeaVim and I see that the plugin has a config property: "Force dialog into normal mode". However, the popup always starts in insert mode. This is an issue because I then have to press Escape first to be able to select an item.

Am I maybe missing something?

Thanks for a great plugin!

**Comment by jphalip** [comment]
I assume it's due to this line? https://github.com/AlexGirardDev/HarpoonIJ/blob/12625f88af1a819e58bac785dbb43388ebc90a7f/src/main/java/ca/alexgirard/harpoonIJ/HarpoonDialog.java#L69

**Comment by AlexGirardDev** [comment]
ya this featrure is just broken currently, they have been doing a pretty large rewrite / refactor of the vim plugin over the past 2 years and its broken this feature a couple times as what i"m trying to do isn"t really supported. i have mostly gotten it to work through hacks. 

I will try and see if i can fix it this weekend though because it has also been bothering me

**Comment by AlexGirardDev** [comment]
i think i have resolved this with the latest version of the plugin, if its not fixed for you can you tell me what IDE you are running / also what OS you are on?

**Comment by jphalip** [comment]
Thanks for following up. I assume maybe the latest version hasn't been published yet? I'm only seeing 0.1.8 right now.

**Comment by AlexGirardDev** [comment]
ya, there was a compatibily issue,i was the email from intelij saying the status changed and just assumed it was approved.

i submitted a new versioun 2 days ago so it shoud be approved shortly

**Comment by AlexGirardDev** [comment]
ok, version 0.2 is now live which should resolve this issue

**Comment by jphalip** [comment]
I confirm the new version works, thank you!

**Comment by t-ober** [comment]
@AlexGirardDev : Unfortunately I think the same issue is back. Could you maybe take another look ?
